import { ROTATION, ModelConfig } from "./modelRotation";
import { generateIdea } from "./providers";
import { supabase, Idea } from "./supabase";
import { sendEmail } from "./email";
import * as fs from "fs";
import * as path from "path";

export const CLAUDE_SYSTEM_PROMPT = `You are a pragmatic product strategist and senior engineer working alongside a solo founder.
Your job is to identify ONE real, specific pain point — in any industry, profession, or daily
workflow — and design a tightly scoped software tool that solves it.

The tool you design must:
- Complement existing platforms and workflows, never compete with them
- Be narrow enough to build completely, broad enough to expand later
- Produce output detailed enough for a downstream implementation agent to begin coding immediately

Today's date: [INSERT DATE]

## PHASE 1 — DISCOVERY (internal reasoning, do not output this phase)

Before generating anything, silently work through this discovery process:

**Step 1 — Cast wide.**
Think across ALL of these territories without defaulting to any one:
- Trades and field workers (electricians, plumbers, HVAC, contractors, landscapers)
- Licensed professionals (accountants, lawyers, dentists, vets, therapists, mortgage brokers)
- Local and independent businesses (salons, gyms, repair shops, restaurants, clinics)
- Creators and solo operators (writers, consultants, coaches, freelancers, agencies)
- Back-office and admin workers (operations, HR, procurement, compliance, logistics)
- Developers and technical teams (code review, incident response, documentation, onboarding)
- Education and training (tutors, course creators, certifications, onboarding workflows)
- Any other human doing something repetitive, error-prone, or manually exhausting

**Step 2 — Find the friction.**
Look for workflows that are:
- Done manually 5+ times a week that software could automate
- Broken handoffs between two systems that don't talk to each other
- A document, form, or report generated by copy-paste or memory
- A task outsourced to a VA or junior employee purely because it's tedious
- A compliance or deadline risk that creates anxiety but no good tooling exists
- Something people are doing in Excel, email, or paper that should have a product

**Step 3 — Validate the pain is real.**
Ask internally:
- Would this person pay $50–$500/month to make this go away?
- Have they already tried to solve it (hired someone, bought a tool, built a workaround)?
- Is the pain recurring, not a one-time setup?

**Step 4 — Design the tool.**
Only after identifying the pain, choose the simplest technology that solves it:
- Could be a browser extension, editor plugin, CLI tool, webhook listener, scheduled job,
  lightweight web app, embeddable widget, API integration layer, desktop app, or mobile utility
- Let the pain dictate the form — do not default to "a SaaS dashboard"
- The tool should slot into the user's existing workflow, not replace it

**Step 5 — Acquisition lens.**
Ask: which larger company would want to own this once it has traction?
- A vertical software vendor in that industry?
- A platform whose ecosystem this tool extends?
- A PE-backed rollup buying workflow tools in that trade or profession?
The tool should be a natural bolt-on, not a standalone empire.

## PHASE 2 — OUTPUT (show this exactly)

---

### 📅 [Today's Date] — [Product Name]: [One-Line Value Proposition]

> *[One sentence: who it's for, what it eliminates, and why it matters now.]*

---

**🎯 1. The Pain**

| Field | Detail |
|---|---|
| **Who** | [Specific person: job title, business type, team size if relevant] |
| **What they do today** | [Exact manual workflow — be visceral and specific] |
| **How often** | [Daily / weekly / per client / per job] |
| **What breaks** | [The failure mode: errors, delays, missed deadlines, lost money, compliance risk] |
| **Current workaround** | [Spreadsheet / VA / copy-paste / nothing / an expensive legacy tool] |
| **Cost of inaction** | [Time lost, dollars lost, risk created, clients churned] |

---

**🔍 2. Why Now**

[1–2 sentences: what has changed recently — a platform API opened up, a regulation changed,
a new capability became affordable, a workflow shifted post-pandemic — that makes this
problem newly solvable or newly urgent.]

---

**🧩 3. The Tool**

- **What it does:** [Plain English description of the core mechanic. One paragraph, no jargon.
  A non-technical person should understand exactly what happens when they use it.]

- **Form factor:** [Browser extension / VS Code plugin / web app / CLI / mobile app /
  Zapier-style integration / scheduled job / embeddable widget / desktop app — whichever
  fits the workflow naturally]

- **What it is NOT:** [Explicitly state what this does not try to do — keeps scope tight
  for the implementation agent]

- **Expansion path:** [One or two natural features or adjacent segments that could be added
  post-launch without rebuilding the core]

---

**📦 4. Distribution**

- **Where they'll find it:** [Specific marketplace, community, subreddit, Slack group,
  professional association, app store, or platform extension store]
- **Discovery trigger:** [The exact moment or search query that leads them to this tool]
- **Acquisition fit:** [Which type of company would acquire this at $500K–$5M once it has
  100–500 paying users, and why it's a natural bolt-on for them]

---

**🔧 5. Implementation Spec**

*This section is structured for a downstream implementation agent.*

**Scope boundary:**
[One sentence defining exactly what the MVP does and does not include.]

**Core data models:**
\`\`\`
[Entity name]
  - field: type (e.g., job_id: uuid)
  - field: type
  - ...

[Entity name]
  - field: type
  - ...
\`\`\`

**File / folder structure:**
\`\`\`
/
├── [folder]/         # [purpose]
│   ├── [file]        # [what it does]
│   └── [file]
├── [folder]/
│   └── ...
└── [entry point]
\`\`\`

**Key APIs or data sources:**
- [API / service name]: [what it provides and why it's used]
- [API / service name]: [what it provides and why it's used]

**Tech stack:**
- **Language/runtime:** [specific choice + version if relevant]
- **Framework:** [specific choice, or "none needed"]
- **Database:** [specific choice, or "none needed"]
- **Auth:** [specific approach — e.g., Clerk, Supabase Auth, OAuth to X platform]
- **Billing:** [Stripe / LemonSqueezy / none for MVP]
- **Hosting:** [Railway / Fly.io / Vercel / browser extension store / etc.]

**The hard part:**
[The one technical challenge that makes this non-trivial to copy. Be specific —
name the API quirk, the parsing problem, the sync edge case, or the domain logic
that requires real engineering judgment.]

**MVP build estimate:**
- [X days] — core mechanic
- [X days] — auth + billing
- [X days] — polish + edge cases
- **Total: [X–Y days] for a shippable MVP**

---

**💰 6. Monetization**

- **Value delivered:** [Time saved / risk eliminated / revenue enabled / compliance achieved]
- **Model:** [Subscription / usage-based / one-time / per-seat — whichever fits naturally]
- **Price anchor:** [What they're paying today for the workaround or alternative]
- **Suggested pricing:** [Specific tier suggestion, e.g., "$49/mo solo, $149/mo team of 5"]
- **Revenue ceiling:** [Rough TAM sanity check — e.g., "50K HVAC businesses in the US,
  10% addressable, $99/mo = ~$60M ARR ceiling at scale — realistic for acquisition target"]`;
/**
 * Reads the fallback provider order from the FALLBACK_PROVIDERS env var.
 * Format: comma-separated entries of "provider:model:label"
 * Example: "anthropic:claude-3-5-sonnet-20241022:Claude 3.5 Sonnet,openrouter:meta-llama/llama-3-70b-instruct:Llama 3 70B"
 * Falls back to a sensible default if the env var is not set.
 */
function getFallbackOrder(): ModelConfig[] {
  const envVal = process.env.FALLBACK_PROVIDERS;
  if (!envVal) {
    console.warn("FALLBACK_PROVIDERS env var not set. Using hardcoded default fallback order.");
    return [
      { provider: "anthropic", model: "claude-3-5-sonnet-20241022", label: "Claude 3.5 Sonnet" },
      { provider: "openrouter", model: "meta-llama/llama-3-70b-instruct", label: "Llama 3 70B" },
      { provider: "gemini", model: "gemini-2.0-flash", label: "Gemini 2.0 Flash" },
    ];
  }

  const entries = envVal.split(",").map((s) => s.trim()).filter(Boolean);
  const configs: ModelConfig[] = [];

  for (const entry of entries) {
    const parts = entry.split(":");
    if (parts.length < 2) {
      console.warn(`Invalid FALLBACK_PROVIDERS entry: "${entry}". Expected format: "provider:model:label". Skipping.`);
      continue;
    }
    const provider = parts[0].trim() as ModelConfig["provider"];
    const model = parts[1].trim();
    const label = parts[2]?.trim() || model;
    configs.push({ provider, model, label });
  }

  if (configs.length === 0) {
    console.warn("FALLBACK_PROVIDERS env var parsed to empty list. Using hardcoded default.");
    return [
      { provider: "anthropic", model: "claude-3-5-sonnet-20241022", label: "Claude 3.5 Sonnet" },
      { provider: "openrouter", model: "meta-llama/llama-3-70b-instruct", label: "Llama 3 70B" },
      { provider: "gemini", model: "gemini-2.0-flash", label: "Gemini 2.0 Flash" },
    ];
  }

  return configs;
}

/**
 * Normalizes a title string for hashing.
 * Strips special chars, emoji, lowercases, and trims whitespace.
 */
export function normalizeForHash(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^\w\s]/g, "") // remove punctuation, emoji, special chars
    .replace(/\s+/g, " ")    // collapse whitespace
    .trim();
}

/**
 * Computes a SHA-256 hex hash of a string using the Web Crypto API.
 * Falls back to a simple string hash if crypto is unavailable.
 */
export async function computeHash(input: string): Promise<string> {
  try {
    const encoder = new TextEncoder();
    const data = encoder.encode(input);
    const hashBuffer = await crypto.subtle.digest("SHA-256", data);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
  } catch {
    // Fallback: simple hash for environments without Web Crypto
    let hash = 0;
    for (let i = 0; i < input.length; i++) {
      const char = input.charCodeAt(i);
      hash = (hash << 5) - hash + char;
      hash |= 0;
    }
    return Math.abs(hash).toString(16);
  }
}

/**
 * Attempts to parse the title and date from generated content.
 */
function parseTitleAndDate(content: string): { title: string; dateLabel: string } {
  let title = "Daily Innovation Idea";
  let dateLabel = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const titleLineMatch = content.match(/### 📅\s*([^-—]+)[-—]\s*([^:]+):/i) || content.match(/###\s*📅?\s*([^-—\n]+)[-—]\s*([^:\n]+)/i);
  if (titleLineMatch) {
    dateLabel = titleLineMatch[1].trim();
    title = titleLineMatch[2].trim();
  } else {
    const fallbackMatch = content.match(/###\s*(.*)/i);
    if (fallbackMatch) {
      const parts = fallbackMatch[1].split(/[-—:]/);
      if (parts.length >= 2) {
        title = parts[1].trim();
        dateLabel = parts[0].replace(/[📅\s]/g, "").trim() || dateLabel;
      } else {
        title = fallbackMatch[1].trim();
      }
    }
  }

  // Clean any stray markdown symbols from the title
  title = title.replace(/^[📅\s*#—-]+|[📅\s*#—-]+$/g, "").trim();

  return { title, dateLabel };
}

/**
 * Fetches recent ideas (last 30 or 30 days) to build an avoid list for regeneration.
 */
async function fetchRecentTitles(): Promise<string[]> {
  const { data, error } = await supabase
    .from("ideas")
    .select("title")
    .order("created_at", { ascending: false })
    .limit(30);

  if (error || !data) {
    console.warn("Failed to fetch recent ideas for avoid list:", error?.message);
    return [];
  }

  return data.map((row) => row.title).filter(Boolean);
}

/**
 * Output path for local-fallback ideas file.
 */
const LOCAL_FALLBACK_DIR = path.join(process.cwd(), "local-fallback");
const LOCAL_FALLBACK_FILE = path.join(LOCAL_FALLBACK_DIR, "ideas.ndjson");

/**
 * Ensures the local-fallback directory exists, creating it if necessary.
 */
function ensureLocalFallbackDir(): void {
  if (!fs.existsSync(LOCAL_FALLBACK_DIR)) {
    fs.mkdirSync(LOCAL_FALLBACK_DIR, { recursive: true });
    console.log(`[LocalFallback] Created directory: ${LOCAL_FALLBACK_DIR}`);
  }
}

/**
 * Detailed error inspection helper — logs the full shape of an error object.
 */
function logErrorDetails(context: string, error: any): void {
  console.error(`[ErrorDetail] ${context} — BEGIN`);
  console.error(`  message: ${error?.message || "(no message)"}`);
  console.error(`  name: ${error?.name || "(no name)"}`);
  console.error(`  code: ${error?.code || "(no code)"}`);
  console.error(`  status: ${error?.status || error?.statusCode || "(no status)"}`);
  console.error(`  statusText: ${error?.statusText || "(no statusText)"}`);
  if (error?.cause) {
    const cause = error.cause;
    console.error(`  cause.message: ${cause?.message || "(no cause message)"}`);
    console.error(`  cause.code: ${cause?.code || "(no cause code)"}`);
    console.error(`  cause.errno: ${cause?.errno || "(no cause errno)"}`);
    console.error(`  cause.syscall: ${cause?.syscall || "(no cause syscall)"}`);
  }
  if (error?.stack) {
    // Log just the first few lines of stack to avoid noise
    const stackLines = error.stack.split("\n").slice(0, 4).join("\n");
    console.error(`  stack (truncated):\n${stackLines}`);
  }
  console.error(`[ErrorDetail] ${context} — END`);
}

/**
 * Checks Supabase connectivity with a lightweight health request.
 * Returns true if reachable, false otherwise. Never throws.
 */
async function checkSupabaseConnectivity(): Promise<boolean> {
  try {
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL || "";
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 8000); // 8s timeout

    const response = await fetch(supabaseUrl.replace(/\/+$/, "") + "/rest/v1/", {
      method: "GET",
      headers: {
        "Accept": "application/json",
        "Content-Type": "application/json",
      },
      signal: controller.signal,
    });

    clearTimeout(timeout);
    const reachable = response.ok || response.status < 500;
    if (!reachable) {
      console.warn(`[SupabaseHealth] Responded with status ${response.status} — treating as unreachable.`);
    }
    return reachable;
  } catch (err: any) {
    logErrorDetails("Supabase connectivity check", err);
    console.warn("[SupabaseHealth] Failed to reach Supabase. Will use local-filesystem fallback if generation succeeds.");
    return false;
  }
}

/**
 * Saves an idea to the local filesystem as NDJSON (one JSON object per line).
 * Never throws — logs errors and returns the file path on success.
 */
function saveIdeaToLocalFilesystem(
  content: string,
  provider: string,
  modelLabel: string,
  attemptInfo?: string
): { filePath: string; title: string } | null {
  try {
    ensureLocalFallbackDir();
    const { title, dateLabel } = parseTitleAndDate(content);
    const normalized = normalizeForHash(title);
    // computeHash is async but we do a best-effort sync fallback hash
    const contentHash = Math.abs(
      normalized.split("").reduce((acc, c) => ((acc << 5) - acc + c.charCodeAt(0)) | 0, 0)
    ).toString(16);

    const entry = {
      saved_at: new Date().toISOString(),
      title,
      date_label: dateLabel,
      content,
      provider,
      model_label: modelLabel,
      content_hash: contentHash,
      attempt_info: attemptInfo || null,
    };

    const line = JSON.stringify(entry) + "\n";
    fs.appendFileSync(LOCAL_FALLBACK_FILE, line, "utf-8");

    console.log(`[LocalFallback] Idea saved to ${LOCAL_FALLBACK_FILE}`);
    console.log(`[LocalFallback] Title: "${title}"`);
    return { filePath: LOCAL_FALLBACK_FILE, title };
  } catch (fsError: any) {
    logErrorDetails("Local filesystem save", fsError);
    return null;
  }
}

/**
 * Checks if a generated title's hash already exists in the database.
 * Includes detailed error logging if the DB query fails.
 */
async function isDuplicateTitle(title: string): Promise<boolean> {
  const normalized = normalizeForHash(title);
  const hash = await computeHash(normalized);

  const { data, error } = await supabase
    .from("ideas")
    .select("id")
    .eq("content_hash", hash)
    .limit(1);

  if (error) {
    logErrorDetails("isDuplicateTitle query", error);
    console.warn("Failed to check for duplicate title:", error.message);
    return false;
  }

  return data !== null && data.length > 0;
}

/**
 * Saves a successfully generated idea to Supabase with a content hash.
 * Includes detailed error logging if the insert fails.
 */
async function saveIdea(
  content: string,
  provider: string,
  modelLabel: string
): Promise<Idea | null> {
  const { title, dateLabel } = parseTitleAndDate(content);
  const normalized = normalizeForHash(title);
  const contentHash = await computeHash(normalized);

  const { data: newIdea, error: insertError } = await supabase
    .from("ideas")
    .insert({
      title,
      date_label: dateLabel,
      content,
      provider,
      model_label: modelLabel,
      sent_email: false,
      content_hash: contentHash,
    })
    .select()
    .single();

  if (insertError) {
    logErrorDetails("saveIdea insert", insertError);
    console.error("Failed to save new idea to Supabase:", insertError.message);
    return null;
  }

  return newIdea as Idea;
}

/**
 * Sends the email notification and marks the idea as emailed on success.
 */
async function sendAndMarkEmail(savedIdea: Idea): Promise<void> {
  console.log("Sending email notification to recipient...");
  const emailSent = await sendEmail({
    title: savedIdea.title,
    dateLabel: savedIdea.date_label,
    content: savedIdea.content,
    modelLabel: savedIdea.model_label,
    ideaId: savedIdea.id,
  });

  if (emailSent) {
    await supabase.from("ideas").update({ sent_email: true }).eq("id", savedIdea.id);
    savedIdea.sent_email = true;
  }
}

/**
 * Attempts to generate content by trying fallback providers in order.
 * Returns { content, provider, modelLabel } or null if all fail.
 */
async function generateWithFallback(prompt: string): Promise<{ content: string; provider: string; modelLabel: string } | null> {
  const fallbackOrder = getFallbackOrder();
  console.log(`Fallback provider order: ${fallbackOrder.map((m) => m.label).join(" → ")}`);

  for (const modelConfig of fallbackOrder) {
    console.log(`Attempting generation with ${modelConfig.provider} (${modelConfig.label})...`);

    try {
      const result = await generateIdea(modelConfig, prompt);
      console.log(`Successfully generated idea with ${modelConfig.provider} (latency: ${result.latencyMs}ms)`);
      return { content: result.text, provider: modelConfig.provider, modelLabel: modelConfig.label };
    } catch (attemptError: any) {
      console.warn(
        `${modelConfig.provider} (${modelConfig.label}) failed: ${attemptError?.message || attemptError}. Trying next provider...`
      );
      // Continue to next provider in the fallback chain
    }
  }

  return null;
}

/**
 * Maximum number of regeneration attempts to find a unique idea.
 */
const MAX_DEDUP_RETRIES = 3;

/**
 * Result type that includes optional fallback info.
 */
export interface PipelineResult {
  success: boolean;
  idea?: Idea;
  error?: string;
  fallbackMode?: boolean;
  fallbackFile?: string;
  fallbackTitle?: string;
}

export async function runIdeaGenerationAndEmailPipeline(): Promise<PipelineResult> {
  // 0. Check Supabase connectivity BEFORE generating — avoid wasting the LLM call
  console.log("[Pipeline] Checking Supabase connectivity...");
  const supabaseHealthy = await checkSupabaseConnectivity();

  if (!supabaseHealthy) {
    console.warn("[Pipeline] ⚠️  Supabase is unreachable. Pipeline will run in local-fallback mode.");
    console.warn("[Pipeline] Ideas will be saved to local-fallback/ directory. They will NOT be emailed.");
  }

  try {
    // 1. If Supabase is reachable, verify the ideas table exists
    if (supabaseHealthy) {
      const { error: tableError } = await supabase.from("ideas").select("id", { count: "exact", head: true });
      if (tableError) {
        logErrorDetails("table existence check", tableError);
        // Don't abort — fallback to local filesystem
        console.error("[Pipeline] Supabase table check failed, falling back to local-filesystem mode.");
        return await runGenerationOnlyWithLocalFallback();
      }
    }

    // 2. Generate with dedup circuit — retry up to MAX_DEDUP_RETRIES times
    let attempt = 0;

    while (attempt <= MAX_DEDUP_RETRIES) {
      let prompt = CLAUDE_SYSTEM_PROMPT;

      // On retry 1+, inject avoid list of recent titles (only if Supabase is reachable)
      if (attempt > 0 && supabaseHealthy) {
        const recentTitles = await fetchRecentTitles();
        if (recentTitles.length > 0) {
          const avoidList = recentTitles
            .map((t) => `- ${t}`)
            .join("\n");
          prompt +=
            `\n\nPreviously generated ideas — DO NOT reuse any of these product names or concepts. Generate something completely different:\n${avoidList}`;
          console.log(`Retry ${attempt}: injecting ${recentTitles.length} existing titles into prompt to avoid duplicates.`);
        }
      }

      // 3. Generate content using fallback providers
      const result = await generateWithFallback(prompt);
      if (!result) {
        return {
          success: false,
          error: "All providers failed to generate an idea. Check generation_logs in Supabase for details.",
        };
      }

      const { title } = parseTitleAndDate(result.content);

      // 4. If Supabase is reachable, check for duplicates
      if (supabaseHealthy) {
        const duplicate = await isDuplicateTitle(title);
        if (duplicate) {
          console.warn(`Duplicate detected: "${title}" already exists. Re-generating... (attempt ${attempt + 1}/${MAX_DEDUP_RETRIES})`);
          attempt++;
          continue;
        }
      }

      // 5. Try to save to Supabase. If it fails or Supabase is down, fallback to local filesystem.
      if (supabaseHealthy) {
        const savedIdea = await saveIdea(result.content, result.provider, result.modelLabel);
        if (savedIdea) {
          // 5a. Send the notification email
          await sendAndMarkEmail(savedIdea);
          return { success: true, idea: savedIdea };
        }
        // saveIdea failed — log was already emitted by logErrorDetails inside saveIdea
        console.warn("[Pipeline] saveIdea failed, falling back to local filesystem...");
      }

      // 5b. Fallback: save to local filesystem
      const fallbackResult = saveIdeaToLocalFilesystem(
        result.content,
        result.provider,
        result.modelLabel,
        supabaseHealthy ? "saveIdea failed" : "Supabase unreachable"
      );

      if (fallbackResult) {
        return {
          success: true,
          idea: undefined,
          fallbackMode: true,
          fallbackFile: fallbackResult.filePath,
          fallbackTitle: fallbackResult.title,
        };
      }

      // 5c. Even local filesystem save failed — unexpected
      return {
        success: false,
        error: "Generated idea could not be saved to either Supabase or local filesystem.",
      };
    }

    // Exhausted all retries without success
    return {
      success: false,
      error: `Failed to generate a unique idea after ${MAX_DEDUP_RETRIES + 1} attempts. Too many duplicates detected.`,
    };
  } catch (err: any) {
    logErrorDetails("runIdeaGenerationAndEmailPipeline top-level", err);
    return { success: false, error: err?.message || String(err) };
  }
}

/**
 * Quick path: generate an idea and save to local filesystem only.
 * Used when Supabase is known unreachable.
 */
async function runGenerationOnlyWithLocalFallback(): Promise<PipelineResult> {
  console.log("[Pipeline-Fallback] Running generation-only mode (local filesystem).");

  const result = await generateWithFallback(CLAUDE_SYSTEM_PROMPT);
  if (!result) {
    return {
      success: false,
      error: "All providers failed to generate an idea in fallback mode.",
    };
  }

  const fallbackResult = saveIdeaToLocalFilesystem(
    result.content,
    result.provider,
    result.modelLabel,
    "Supabase unreachable — fallback mode"
  );

  if (!fallbackResult) {
    return {
      success: false,
      error: "Idea generated but failed to save to local filesystem.",
    };
  }

  return {
    success: true,
    fallbackMode: true,
    fallbackFile: fallbackResult.filePath,
    fallbackTitle: fallbackResult.title,
  };
}
