import { Resend } from "resend";

export async function sendEmail({
  title,
  dateLabel,
  content,
  modelLabel,
  ideaId,
}: {
  title: string;
  dateLabel: string;
  content: string;
  modelLabel: string;
  ideaId: string;
}) {
  const apiKey = process.env.RESEND_API_KEY;
  const fromEmail = process.env.RESEND_FROM_EMAIL || "noreply@spark.srivedanthtek.com";
  const myEmail = process.env.MY_EMAIL || "sindhumuthyam@gmail.com";
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://spark.srivedanthtek.com";

  if (!apiKey) {
    console.error("Missing RESEND_API_KEY environment variable. Email cannot be sent.");
    return false;
  }

  const resend = new Resend(apiKey);

  // Convert some headers or list elements to clean HTML manually
  let formattedHtml = content
    .replace(/^### (.*$)/gim, '<h3 style="font-family: Georgia, serif; color: #1a1a1a; margin-top: 24px; margin-bottom: 8px;">$1</h3>')
    .replace(/^\*\*([^*]+)\*\*/gim, '<strong style="color: #1a1a1a;">$1</strong>')
    .replace(/^\* (.*$)/gim, '<li style="margin-bottom: 6px;">$1</li>')
    .replace(/^- (.*$)/gim, '<li style="margin-bottom: 6px;">$1</li>')
    .replace(/\n\n/g, '<br/><br/>');

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <title>✦ Spark — ${title}</title>
      </head>
      <body style="font-family: 'Inter', -apple-system, sans-serif; background-color: #ffffff; color: #1a1a1a; margin: 0; padding: 40px 20px; -webkit-font-smoothing: antialiased;">
        <div style="max-width: 600px; margin: 0 auto;">
          <div style="border-bottom: 1px solid #eaeaea; padding-bottom: 20px; margin-bottom: 30px;">
            <p style="font-size: 14px; color: #6b7280; margin: 0; text-transform: uppercase; letter-spacing: 0.05em;">✦ Spark Daily Idea</p>
            <h1 style="font-family: Georgia, serif; font-size: 28px; margin: 10px 0 5px 0; color: #1a1a1a; font-weight: normal;">${title}</h1>
            <p style="font-size: 14px; color: #6b7280; margin: 0;">
              ${dateLabel} &middot; <span style="background-color: #f3f4f6; padding: 2px 6px; border-radius: 4px; font-size: 12px; font-weight: 500;">${modelLabel}</span>
            </p>
          </div>
          
          <div style="font-family: Georgia, serif; font-size: 16px; line-height: 1.6; color: #1a1a1a;">
            ${formattedHtml}
          </div>
          
          <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #eaeaea; text-align: center;">
            <a href="${siteUrl}/ideas/${ideaId}" style="display: inline-block; background-color: #1a1a1a; color: #ffffff; text-decoration: none; padding: 12px 24px; border-radius: 6px; font-weight: 500; font-size: 15px; margin-bottom: 20px;">Read on Spark &rarr;</a>
            <p style="font-size: 12px; color: #9ca3af; margin: 0;">Generated by: ${modelLabel}</p>
            <p style="font-size: 11px; color: #9ca3af; margin: 5px 0 0 0;">Generated daily by Claude &middot; spark.srivedanthtek.com</p>
          </div>
        </div>
      </body>
    </html>
  `;

  try {
    const response = await resend.emails.send({
      from: `Spark <${fromEmail}>`,
      to: [myEmail],
      subject: `✦ Spark — ${title} · ${modelLabel} · ${dateLabel}`,
      html,
    });

    if (response.error) {
      console.error("Resend email delivery failed:", response.error);
      return false;
    }

    return true;
  } catch (error) {
    console.error("Exception occurred while sending email with Resend:", error);
    return false;
  }
}